echo Executing NeXTTool to upload /Applications/robolab/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
 /Applications/robolab/nxtOSEK/bin/nexttool /COM=usb -firmware=/Applications/robolab/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
